### PR TITLE
Support setting the image tintColor.

### PR DESCRIPTION
**Pull request by Zandor300**
Support setting the `tintColor` of the `UIImageView`. This is useful for template images.

### CODE REVIEW

**Comment by Zandor300** [comment]
@alberdev

**Comment by alberdev** [comment]
Perfect! Thank you! ;)

**Comment by Zandor300** [comment]
@alberdev Could you release a new version with the change?

**Comment by alberdev** [comment]
Hi @Zandor300 ! 
1.1.0 released!

**Comment by Zandor300** [comment]
@alberdev Thanks!

**Pull request merged**
